### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by mishrabiswajit** [PixelOS-Pixelish/official_devices#2]
## Name and Codename of the device you want to apply for 
Realme 5 Series (RMX1911, RMX2030, RMX1925 ,RMX1927) (unified codename "r5x")

## Device Tree sources

https://github.com/mishrabiswajit/device_realme_r5x
https://github.com/mishrabiswajit/kernel_realme_r5x
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_realme_r5x

## What ROM's do you maintain officially/unofficially
AWAKEN OS , PIXEL OS

## How long have you been building Custom ROMs
2 months

## Any Exceptions/special concern?
NO

### Telegram username
@yourdeathiswaitingforyou

### GitHub username
@mishrabiswajit

**Comment by mishrabiswajit** [comment]
FBE enabled now

**Comment by whyredfire** [comment]
> fbe is disabled as Twrp don't support encryption yet for 12

Doesn't matter actually, you can still end up sideloading zips or flash via sdcard.

**Comment by itsmethekid** [comment]
@whyredfire FBE moment

**Comment by itsmethekid** [comment]
@itsmethekid i just opned this link

**Comment by whyredfire** [comment]
Considering the fact that you're applying for the third time

  1. Your commits don't have proper authorship, like [here](https://github.com/mishrabiswajit/device_realme_r5x/commit/1faa93ed3bc75e5bae30b10f8b2e52323d8a2985) and [here](https://github.com/mishrabiswajit/device_realme_r5x/commit/bea96bc5590d0fde50c9d1b27424235533a30f7f), violates [this](https://github.com/PixelOS-Pixelish/official_devices/blob/twelve/docs/guidelines.md?plain=1#L3).
  2. You added a lot of placebo props in [this](https://github.com/mishrabiswajit/device_realme_r5x/commit/2c020b5f6d9922403f6e60ce487b8cd6a0b069e7) commit here which violates [this](https://github.com/PixelOS-Pixelish/official_devices/blob/twelve/docs/devicereq.md?plain=1#L12).
  3.  You should've inherited [common_full_phone.mk](https://github.com/PixelOS-Pixelish/vendor_aosp/blob/twelve/config/common_full_phone.mk) instead of just common.mk in makefile for including apn config and telephony packages.
  4. FBE is disabled which violates [this](https://github.com/PixelOS-Pixelish/official_devices/blob/twelve/docs/devicereq.md?plain=1#L14).
  5. You're underexperienced and almost no contribution in your trees.
